# Generated by Django 4.0.4 on 2022-08-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.IntegerField(default=6),
        ),
    ]
